### ISSUE TITLE
No modul future gan

### ISSUE THREAD

**Issue by widiit** [41Team/RoutersploitTermux#2]
$ python rsf.py
Traceback (most recent call last):                                                        File "rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/data/data/com.termux/files/home/routersploit/routersploit/interpreter.py", line 11, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'

Sudaj coba install future, ternyata sudah terinstall mohon arahannya

**Comment by widiit** [comment]
Ternyata pake ini gan..!!
It works..

python3 -m pip install -r requirements.txt
